name: brainclamp
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - h5py>=3.8.0
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - notebook
  - nbconvert
  - pip:
    - torch>=2.0.0
    - torchvision>=0.15.0
    - torchaudio>=2.0.0
    - optuna>=3.0.0
    - tensorboard>=2.13.0
    - wandb>=0.15.0
    - nbstripout>=0.6.0
